#!/bin/bash
pkgname='taapcrunchyroll-bot'

configDir="$HOME/.config/taapcrunchyroll-bot"

configFile="$configDir/taapcrunchyroll-bot.conf"
CHAT_ID=""
TOKEN=""
source "$configFile"
[ -z $CHAT_ID ] && echo -n "CHAT_ID" && read CHAT_ID
[ -z $TOKEN ] && echo -n "TOKEN" && read TOKEN
pythonScriptFolder="/usr/lib/$pkgname" 
python3 "$pythonScriptFolder/taapmessage.py" "$TOKEN" "$CHAT_ID" "$@"
