#!/bin/bash

pkgname='taapcrunchyroll-bot'

configDir="$HOME/.config/taapcrunchyroll-bot"
configFile="$configDir/taapcrunchyroll-bot.conf"
if [ ! -e "$configDir" ]; then 
        mkdir -p "$configDir"
fi 
if [ ! -e "$configFile" ]; then 
        touch "$configFile"
fi 
exec > >(tee -i "$configDir/bot.log")
exec 2>&1

numberOfGroups=1
getCredentialsScript=0
updateUserInfoScript=0
killTime=36000 #12 hours
loop=2
source "$configFile"


echo "numberOfGroups '$numberOfGroups'"
echo "getCredentialsScript '$getCredentialsScript'"
echo "updateUserInfoScript '$updateUserInfoScript'"

echo "errorScript '$updateUserInfoScript'"
echo "killTime '$killTime'"

cd "$configDir" || exit 2
pythonScriptFolder="/usr/lib/$pkgname" 


for i in $(seq 1 $numberOfGroups);
    do  
        n=$loop
        while [[ $loop -le 0 || $n -ne 0 ]]; do
            n=$n-1
            credentials=$($getCredentialsScript "$i")
            uname=$(echo "$credentials" |cut -d " " -f1)
            if [ "$credentials" != "0" ]; then
                echo "Obtaining guest pass for $uname of Group $i";
                
                python3 "$pythonScriptFolder/crunchyrollGuestPassFinder.py" $credentials "$killTime"
                errorCode="$?"
                if [[ $errorCode -eq 0 ]]; then
	                echo "Guest pass obtained; Updating user info" 
                else
                    echo "exited with error code $errorCode"
                fi
                
                $updateUserInfoScript $errorCode "$i" $credentials
                
            else
                echo "Account '$uname' is still activated"

            fi
       done
  done
